image:
  name: hashicorp/terraform
  entrypoint: [""]

deploy-job:
  only:
    refs:
      - main
    changes:
      - deployed-projects/**/*.tf
      - deployed-projects/**/*.tfvars
  variables:
    TF_VAR_harbor_url: https://harbor.fly-env.fly.bjv.me
  before_script:
    - git config --global user.email "project-onboarding-gitlab-runner@example.com"
    - git config --global user.name "Gitlab Runner - Terraforming Projects"
    - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh ke
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git fetch origin main && git checkout main
    - 'mkdir -p ~/.kube && echo "$KUBECONFIG_CONTENT" > ~/.kube/tf-config'
    - './gitlab-scripts/terraform-apply-projects.sh'

