image:
  name: hashicorp/terraform
  entrypoint: [""]

deploy-job:
  only:
    refs:
      - main
    changes:
      - deployed-projects/**/*
  variables:
    TF_VAR_harbor_url: https://harbor.fly-env.fly.bjv.me
  before_script:
    - git config --global user.email "project-onboarding-gitlab-runner@example.com"
    - git config --global user.name "Gitlab Runner - Terraforming Projects"
  script:
    - 'mkdir -p ~/.kube && echo "$KUBECONFIG_CONTENT" > ~/.kube/tf-config'
    - './gitlab-scripts/terraform-apply-projects.sh'

