stages:
  - deploy

image:
  name: hashicorp/terraform
  entrypoint: ["/bin/sh"]

build_a:
  stage: deploy
  script:
    - 'git diff --name-only HEAD~5 | grep deployed-projects | xargs dirname | cut -d "/" -f2 | sort | uniq'

